### ISSUE TITLE
'Ç' pode quebrar os módulos totalmente.

### ISSUE THREAD

**Issue by catupiyuri** [Desuoka/CVEngine#1]
É de conhecimento que no título de janela de um módulo um simples 'ç' pode quebrar totalmente o código. Pode abrir muitas (e muitas) cópias do mesmo módulo até que o computador crashe ou trave totalmente. **NÃO É RECOMENDADO TROCAR O NOME DOS MÓDULOS. Isso é bug do OpenCV, sinto muito.**

**Comment by catupiyuri** [comment]
[Gravação de tela de 2024-04-28 00-12-05.webm](https://github.com/Desuoka/CVEngine/assets/94811009/16a737e7-9e32-4d64-9702-5fcde8110556)

**Comment by Desuoka** [comment]
E SIM, isso também afeta Windows. Eu não sou responsável por dispositivos bloqueados, cartões SD mortos, guerra termonuclear ou se você foi demitido porque o computador explodiu! Eu avisei.

**Comment by catupiyuri** [comment]
E SIM, isso também afeta Windows. Eu não sou responsável por dispositivos bloqueados, cartões SD mortos, guerra termonuclear ou se você foi demitido porque o computador explodiu! Eu avisei.

**Comment by lucmsilva651** [comment]
kd remover o ç

**Comment by fuyukihidekii** [comment]
> kd remover o ç

KD remover python, gnome e arch
