### ISSUE TITLE
Disclaimer: we're friends!

### ISSUE THREAD

**Issue by fuyukihidekii** [Desuoka/CVEngine#9]
for anyone else reading this, we (desuoka, lucmsilva, ralsei and me) are all friends and just trolling around. There's no hate or actual "git bully" lol :)

I don't use arch btw, and I need my beloved debian / opensuse support right now

**Comment by lucmsilva651** [comment]
git bully!!!

**Comment by catupiyuri** [comment]
We all love each other. Don't worry, i love them.

They're just a little bit stupid XD. 

# (HECK NO SUSE DEBIAN SUMPOT!!!11!)

**Comment by fuyukihidekii** [comment]
> git bully!!!

BULLY MAGUIRE

**Comment by fuyukihidekii** [comment]
> We all love each other. Don't worry, i love them.
> 
> They're just a little bit stupid XD.
> 
> # (HECK NO SUSE DEBIAN SUMPOT!!!11!)

don't dare you support windows and exclude my babies
